
monolog:
  channels: ['filemaker']
  handlers:
    main:
      type: fingers_crossed
      action_level: error
      handler: nested
    nested:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
    console:
      type: console
      channels: [ '!event' ]
    # dedicated handler for FileMaker-related logs
    filemaker:
      type: stream
      path: "%kernel.logs_dir%/filemaker.log"
      level: info
      channels: [ 'filemaker' ]
